### ISSUE TITLE
Release the package

### ISSUE THREAD

**Issue by yordis** [ueberauth/guardian_phoenix#2]
We need to release `guardian` first and fix the dependency on this package.

**Comment by doomspork** [comment]
@yordis do you wanna open a PR for guardian to bump versions et al?

**Comment by yordis** [comment]
@doomspork did you released guardian?

**Comment by doomspork** [comment]
No @yordis, we still need to bump the `mix.exs` and what not in that repo, that's what I was asking you about above 😁Do you want to do that? Otherwise I can get to it tomorrow.

**Comment by yordis** [comment]
Ahhhhhhh jeez, will do, let me write some changelog in `guardian` and publish it to Hex.

**Comment by yordis** [comment]
Favor of https://github.com/ueberauth/guardian_phoenix/pull/3
