### ISSUE TITLE
Phoenix 1.5 support

### ISSUE THREAD

**Issue by agramichael** [ueberauth/guardian_phoenix#7]
Any plans to update the library to support Phoenix 1.5?

I tried bumping the version locally. Everything seems to work although tests are broken.

**Comment by Hanspagh** [comment]
Hi @agramichael. Would you mind sharing the code?

**Comment by agramichael** [comment]
@Hanspagh https://github.com/realyarilabs/guardian_phoenix

**Comment by Hanspagh** [comment]
I have fixed the test and updated the test here #8
